<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CorregimientoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('corregimientos')->insert([
            //PROVINCIA DE BOCAS DEL TORO
            //Almirante
            ['name' => 'Almirante', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bajo Culubre', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barrio Francés', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barriada Guaymí', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cauchero', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ceiba', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Miraflores', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nance de Risco', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Valle de Aguas Arriba', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Valle del Risco', 'idDistrito' => 1, 'codigoUbicacion' => 'N/A'],
            //Bocas del Toro
            ['name' => 'Bastimentos', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bocas del Drago', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bocas del Toro', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Punta Laurel', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Cristobal', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tierra Oscura', 'idDistrito' => 2, 'codigoUbicacion' => 'N/A'],
            //Changuinola
            ['name' => 'Barranco Adentro', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barriada 4 de Abril', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Changuinola', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cochigro', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Empalme', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Silencio', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 12', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 30', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 4', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 51', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 6', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 60', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Finca 66', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guabito', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Gloria', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Mesa', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Delicias', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Tablas', 'idDistrito' => 3, 'codigoUbicacion' => 'N/A'],
            //Chiriqui Grande
            ['name' => 'Bajo Cedro', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chiriquí Grande', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Miramar', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Punta Peña', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Punta Robalo', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rambala', 'idDistrito' => 4, 'codigoUbicacion' => 'N/A'],

            //COCLE
            //Aguadulce
            ['name' => 'Aguadulce', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barrios Unidos', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cristo', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Hato de San Juan de Dios', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Roble', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pocrí', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pueblos Unidos', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Virgen del Carmen', 'idDistrito' => 5, 'codigoUbicacion' => 'N/A'],
            //Anton
            ['name' => 'Antón', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Caballero', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cabuya', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Chirú', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Retiro', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Valle', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Juan Díaz', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Hato', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan de Dios', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Rita', 'idDistrito' => 6, 'codigoUbicacion' => 'N/A'],
            //La Pintada
            ['name' => 'El Harino', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Potrero', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Pintada', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Lomas', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Grande', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Norte', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Piedras Gordas', 'idDistrito' => 7, 'codigoUbicacion' => 'N/A'],
            //Nata
            ['name' => 'Capellanía', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Caño', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guzmán', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Huacas', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Natá de los Caballeros', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Toza', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Villarreal', 'idDistrito' => 8, 'codigoUbicacion' => 'N/A'],
            //Ola
            ['name' => 'El Copé', 'idDistrito' => 9, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Palmar', 'idDistrito' => 9, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Picacho', 'idDistrito' => 9, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Pava', 'idDistrito' => 9, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Olá', 'idDistrito' => 9, 'codigoUbicacion' => 'N/A'],
            //Penonome
            ['name' => 'Boca de Tucué', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Candelario Ovalle', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cañaveral', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Coclé', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'General Victoriano Lorenzo', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chiguirí Arriba', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Coco', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Minas', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pajonal', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Penonomé', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Riecito', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Grande', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Indio', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Miguel', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Toabré', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tulú', 'idDistrito' => 10, 'codigoUbicacion' => 'N/A'],

            //COLON
            //Chagres
            ['name' => 'Achiote', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Guabo', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Encantada', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nuevo Chagres', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palmas Bellas', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Piña', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Salud', 'idDistrito' => 11, 'codigoUbicacion' => 'N/A'],
            //Colon
            ['name' => 'Barrio Norte', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barrio Sur', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Buena Vista', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cativá', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ciricito', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Criostóbal', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Criostóbal Este', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Escobal', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Limón', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nueva Probidencia', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Puerto Pilón', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sabanitas', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Salamanca', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Rosa', 'idDistrito' => 12, 'codigoUbicacion' => 'N/A'],
            //Donoso
            ['name' => 'Coclé del Norte', 'idDistrito' => 13, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Guásimo', 'idDistrito' => 13, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Gobea', 'idDistrito' => 13, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Miguel de la Borda', 'idDistrito' => 13, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Indio', 'idDistrito' => 13, 'codigoUbicacion' => 'N/A'],
            //Omar Torrijos Herrera
            ['name' => 'Nueva Esperanza', 'idDistrito' => 14, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José del General', 'idDistrito' => 14, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan de Turbe', 'idDistrito' => 14, 'codigoUbicacion' => 'N/A'],
            //Portobelo
            ['name' => 'Cacique', 'idDistrito' => 15, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Garrote', 'idDistrito' => 15, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Isla Grande', 'idDistrito' => 15, 'codigoUbicacion' => 'N/A'],
            ['name' => 'María Chiquita', 'idDistrito' => 15, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Portobelo', 'idDistrito' => 15, 'codigoUbicacion' => 'N/A'],
            //Santa Isabel
            ['name' => 'Cuango', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Miramar', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nombre de Dios', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palenque', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palmira', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Playa Chiquita', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Isabel', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Viento Frío', 'idDistrito' => 16, 'codigoUbicacion' => 'N/A'],

            //CHIRIQUI
            //Alanje
            ['name' => 'Alanje', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Canta Gallo', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Divalá', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Tejar', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guarumal', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nuevo México', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palo Grande', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Querévalo', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santo Tomás', 'idDistrito' => 17, 'codigoUbicacion' => 'N/A'],
            //Baru
            ['name' => 'Puerto Armuelles', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Baco', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Palmar', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Limones', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Manaca', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Progreso', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rodolfo Aguilar Delgado', 'idDistrito' => 18, 'codigoUbicacion' => 'N/A'],
            //Boqueron
            ['name' => 'Bagalá', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Boquerón', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cordillera', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guabal', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guayabal', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paraíso', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pedregal', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tijeras', 'idDistrito' => 19, 'codigoUbicacion' => 'N/A'],
            //Boquete
            ['name' => 'Alto Boquete', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bajo Boquete', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Caldera', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Jaramillo', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Naranjos', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palmira', 'idDistrito' => 20, 'codigoUbicacion' => 'N/A'],
            //Bugaba
            ['name' => 'Aserrío de Gariché', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bugaba', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Bongo', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Gómez', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Concepción', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Estrella', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Andrés', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Isidro', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santo Domingo', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Marta', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Rosa', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Solano', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sortová', 'idDistrito' => 21, 'codigoUbicacion' => 'N/A'],
            //David
            ['name' => 'Bijagual', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cochea', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'David', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'David Este', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'David Sur', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chiriquí', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guacá', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Lomas', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pedregal', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Carlos', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Pablo Nuevo', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Pablo Viejo', 'idDistrito' => 22, 'codigoUbicacion' => 'N/A'],
            //Dolega
            ['name' => 'Dolega', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Dos Ríos', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Algarrobos', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Anastacios', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Potrerillos', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Potrerillos Abajo', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rovira', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tinajas', 'idDistrito' => 23, 'codigoUbicacion' => 'N/A'],
            //Gualaca
            ['name' => 'Gualaca', 'idDistrito' => 24, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hornito', 'idDistrito' => 24, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Angeles', 'idDistrito' => 24, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paja de Sombrero', 'idDistrito' => 24, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rincón', 'idDistrito' => 24, 'codigoUbicacion' => 'N/A'],
            //Remedios
            ['name' => 'El Nancito', 'idDistrito' => 25, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Porvenir', 'idDistrito' => 25, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Puerto', 'idDistrito' => 25, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Remedios', 'idDistrito' => 25, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Lucía', 'idDistrito' => 25, 'codigoUbicacion' => 'N/A'],
            //Renacimiento
            ['name' => 'Breñón', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cañas Gordas', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Dominical', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Monte Lirio', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Plaza de Caisán', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Sereno', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Clara', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Cruz', 'idDistrito' => 26, 'codigoUbicacion' => 'N/A'],
            //San Felix
            ['name' => 'Juay', 'idDistrito' => 27, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lajas Adentro', 'idDistrito' => 27, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Lajas', 'idDistrito' => 27, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Félix', 'idDistrito' => 27, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Cruz', 'idDistrito' => 27, 'codigoUbicacion' => 'N/A'],
            //San Lorenzo
            ['name' => 'Boca Chica', 'idDistrito' => 28, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Boca del Monte', 'idDistrito' => 28, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Horconcitos', 'idDistrito' => 28, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan', 'idDistrito' => 28, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Lorenzo', 'idDistrito' => 28, 'codigoUbicacion' => 'N/A'],
            //Tierras Altas
            ['name' => 'Cerro Punta', 'idDistrito' => 29, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cuesta de Piedra', 'idDistrito' => 29, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nueva California', 'idDistrito' => 29, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paso Ancho', 'idDistrito' => 29, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Volcán', 'idDistrito' => 29, 'codigoUbicacion' => 'N/A'],
            //Tole
            ['name' => 'Bella Vista', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Viejo', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cristo', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Justo Fidel Palacios', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lajas de Tolé', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Portero de Caña', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebrada de Piedra', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tolé', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Veladero', 'idDistrito' => 30, 'codigoUbicacion' => 'N/A'],

            //DARIEN
            //Chepigana
            ['name' => 'Camogantí', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chepigana', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Garachiné', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Jaqué', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Palma', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Puerto Piña', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sambú', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Setegantí', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Taimatí', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tucutí', 'idDistrito' => 31, 'codigoUbicacion' => 'N/A'],
            //Pinogana
            ['name' => 'Boca de Cupé', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Comarca Kuna de Wargandí', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Real de Santa María', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Metetí', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paya', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pinogana', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Púcuro', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Yape', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Yaviza', 'idDistrito' => 32, 'codigoUbicacion' => 'N/A'],
            //Santa Fe
            ['name' => 'Agua Fría', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cucunatí', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Congo', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Congo Arriba', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Iglesias', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Fe', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Zapallal', 'idDistrito' => 33, 'codigoUbicacion' => 'N/A'],

            //Herrera
            //Chitre
            ['name' => 'Chitré', 'idDistrito' => 34, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Arena', 'idDistrito' => 34, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Monagrillo', 'idDistrito' => 34, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Bonito', 'idDistrito' => 34, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan Bautista', 'idDistrito' => 34, 'codigoUbicacion' => 'N/A'],
            //Las Minas
            ['name' => 'Chepo', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chumical', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Toro', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Minas', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Leones', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebrara del Rosario', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebrada el Ciprián', 'idDistrito' => 35, 'codigoUbicacion' => 'N/A'],
            //Los Pozos
            ['name' => 'El Capurí', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Calabacito', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cedro', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Arena', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Pitaloza', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Llanas', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Cerritos', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Cerros de Paja', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Pozos', 'idDistrito' => 36, 'codigoUbicacion' => 'N/A'],
            //Ocu
            ['name' => 'Cerro Largo', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Tijera', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Entradero del Castillo', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Llanos', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Grande', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Menchaca', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ocú', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Peñas Chatas', 'idDistrito' => 37, 'codigoUbicacion' => 'N/A'],
            //Parita
            ['name' => 'Cabuya', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Castillos', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano de la Cruz', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'París', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Parita', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Portobelillo', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Potuga', 'idDistrito' => 38, 'codigoUbicacion' => 'N/A'],
            //Pese
            ['name' => 'El Pájaro', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Barrero', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Pedregoso', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Ciruelo', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Cabras', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pesé', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rincón Hondo', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sabanagrande', 'idDistrito' => 39, 'codigoUbicacion' => 'N/A'],
            //Santa Maria
            ['name' => 'Chupampa', 'idDistrito' => 40, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Rincón', 'idDistrito' => 40, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Limón', 'idDistrito' => 40, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Canelos', 'idDistrito' => 40, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa María', 'idDistrito' => 40, 'codigoUbicacion' => 'N/A'],

            //LOS SANTOS
            //Guarare
            ['name' => 'El Espinal', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Hato', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Macano', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guararé', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guararé Arriba', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Enea', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Pasera', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Trancas', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Abajo', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Perales', 'idDistrito' => 41, 'codigoUbicacion' => 'N/A'],
            //Las Tablas
            ['name' => 'Bajo Corral', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bayano', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Carate', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cocal', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Manantial', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Muñoz', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Pedregoso', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Sesteadero', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Laja', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Miel', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Palma', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Tiza', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Palmitas', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Tablas', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Tablas Abajo', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nuario', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Palmira', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Peña Blanca', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Hondo', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Miguel', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santo Domingo', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Valle Rico', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Vallerriquito', 'idDistrito' => 42, 'codigoUbicacion' => 'N/A'],
            //Los Santos
            ['name' => 'Agua Buena', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Ejido', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Guásimo', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Colorada', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Espigadilla', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Villa de Los Santos', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Cruces', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Guabas', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Largo', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Ángeles', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Olivos', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sabana Grande', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Ana', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tres Quebradas', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Villa Lourdes', 'idDistrito' => 43, 'codigoUbicacion' => 'N/A'],
            //Macaracas
            ['name' => 'Bahía Honda', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bajos de Güera', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Corozal', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chupá', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cedro', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Espino Amarillo', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Mesa', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano de Piedra', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Palmas', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Macaracas', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mogollón', 'idDistrito' => 44, 'codigoUbicacion' => 'N/A'],
            //Pedasi
            ['name' => 'Los Asientos', 'idDistrito' => 45, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mariabé', 'idDistrito' => 45, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Oria Arriba', 'idDistrito' => 45, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pedasí', 'idDistrito' => 45, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Purio', 'idDistrito' => 45, 'codigoUbicacion' => 'N/A'],
            //Pocri
            ['name' => 'El Cañafístulo', 'idDistrito' => 46, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lajamina', 'idDistrito' => 46, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paraíso', 'idDistrito' => 46, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Paritilla', 'idDistrito' => 46, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pocrí', 'idDistrito' => 46, 'codigoUbicacion' => 'N/A'],
            //Tonosi
            ['name' => 'Altos de Güera', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cambutal', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cañas', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Bebedero', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cacao', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cortezo', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Flores', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guánico', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Tronosa', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Isla de Cañas', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tonosí', 'idDistrito' => 47, 'codigoUbicacion' => 'N/A'],

            //PANAMA
            //Balboa
            ['name' => 'La Ensenada', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Esmeralda', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Guinea', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pedro González', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Saboga', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Miguel', 'idDistrito' => 48, 'codigoUbicacion' => 'N/A'],
            //Chepo
            ['name' => 'Cañita', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chepillo', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chepo', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Llano', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Margaritas', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Madungandí', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Cruz de Chinina', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tortí', 'idDistrito' => 49, 'codigoUbicacion' => 'N/A'],
            //Chiman
            ['name' => 'Brujas', 'idDistrito' => 50, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chimán', 'idDistrito' => 50, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Gonzalo Vásquez', 'idDistrito' => 50, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pásiga', 'idDistrito' => 50, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Unión Santeña', 'idDistrito' => 50, 'codigoUbicacion' => 'N/A'],
            //Panama
            ['name' => '24 de Diciembre', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Alcalde Díaz', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ancón', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bella Vista', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bethania', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Caimitillo', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Calidonia', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chilibre', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Curundú', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Don Bosco', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Chorrillo', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ernesto Córdoba Campos', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Juan Díaz', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Cumbres', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Garzas', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Mañanitas', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pacora', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Parque Lefevre', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pedregal', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pueblo Nuevo', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Abajo', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Felipe', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Francisco', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Martín', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Ana', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tocumen', 'idDistrito' => 51, 'codigoUbicacion' => 'N/A'],
            //San Miguelito
            ['name' => 'Amelia Denis de Icaza', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Arnulfo Arias', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Belisario Frias', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Belisario Porras', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Jose Domingo Espinar', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mateo Iturralde', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Omar Torrijos', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rufina Alfaro', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Victoriano Lorenzo', 'idDistrito' => 52, 'codigoUbicacion' => 'N/A'],
            //Taboga
            ['name' => 'Otoque Oriente', 'idDistrito' => 53, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Otoque Occidente', 'idDistrito' => 53, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Taboga', 'idDistrito' => 53, 'codigoUbicacion' => 'N/A'],

            //VERAGUAS
            //Atalaya
            ['name' => 'Atalaya', 'idDistrito' => 54, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Barrito', 'idDistrito' => 54, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Carrillo', 'idDistrito' => 54, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Montañuela', 'idDistrito' => 54, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Antonio', 'idDistrito' => 54, 'codigoUbicacion' => 'N/A'],
            //Calobre
            ['name' => 'Barnizal', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Calobre', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chitra', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cocla', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Potrero', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Laguna', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Raya de Calobre', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Tetilla', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Yeguada', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Guías', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Monjarás', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José', 'idDistrito' => 55, 'codigoUbicacion' => 'N/A'],
            //Cañazas
            ['name' => 'Cañazas', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro de Plata', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Aromillo', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Picador', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Cruces', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Valles', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Marcelo', 'idDistrito' => 56, 'codigoUbicacion' => 'N/A'],
            //La Mesa
            ['name' => 'Bisvalles', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Boró', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Higo', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Mesa', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano Grande', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Milagros', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Bartolo', 'idDistrito' => 57, 'codigoUbicacion' => 'N/A'],
            //Las Palmas
            ['name' => 'Cerro de Casa', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Corozal', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El María', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Prado', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Rincón', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Palmas', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Llano de la Cruz', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lolá', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Manuel E. Amador Terrero', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pixvae', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Martín de Porres', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Viguí', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Zapotillo', 'idDistrito' => 58, 'codigoUbicacion' => 'N/A'],
            //Mariato
            ['name' => 'Arenas', 'idDistrito' => 59, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cacao', 'idDistrito' => 59, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mariato', 'idDistrito' => 59, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebro', 'idDistrito' => 59, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tebario', 'idDistrito' => 59, 'codigoUbicacion' => 'N/A'],
            //Montijo
            ['name' => 'Cébaco', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Costa Hermosa', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Gobernadora', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Garceana', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Leones', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Montijo', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Pilón', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Unión del Norte', 'idDistrito' => 60, 'codigoUbicacion' => 'N/A'],
            //Rio de Jesus
            ['name' => 'Catorce de Noviembre', 'idDistrito' => 61, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Castillos', 'idDistrito' => 61, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Huacas', 'idDistrito' => 61, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río de Jesús', 'idDistrito' => 61, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Utira', 'idDistrito' => 61, 'codigoUbicacion' => 'N/A'],
            //San Francisco
            ['name' => 'San Francisco', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Corral Falso', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Hatillos', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Remance', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Juan', 'idDistrito' => 62, 'codigoUbicacion' => 'N/A'],
            //Santa Fe
            ['name' => 'Calovébora', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Alto', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cuay', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Pantano', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Gatú o Gatucito', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Luis', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rubén Cantú', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Fé', 'idDistrito' => 63, 'codigoUbicacion' => 'N/A'],
            //Santiago
            ['name' => 'Canto del Llano', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Carlos Santana Ávila', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Edwin Fábregas', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Colorada', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Peña', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Raya de Santa María', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Algarrobos', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nuevo Santiago', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ponuga', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rodrigo Luque', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Martín de Porres', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Pedro', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santiago', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santiago Este', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santiago Sur', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Urracá', 'idDistrito' => 64, 'codigoUbicacion' => 'N/A'],
            //Sona
            ['name' => 'Bahía Honda', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Calidonia', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cativé', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Marañón', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guarumal', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hicaco', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Soledad', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Trinchera', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebrada de Oro', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Grande', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Rodeo Viejo', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Soná', 'idDistrito' => 65, 'codigoUbicacion' => 'N/A'],

            //PANAMA OESTE
            //Arraijan
            ['name' => 'Arraiján', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Burunga', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Silvestre', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Juan Demóstenes Arosemena', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nuevo Emperador', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Clara', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Vacamonte', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Veracruz', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Vista Alegre', 'idDistrito' => 66, 'codigoUbicacion' => 'N/A'],
            //Capira
            ['name' => 'Caimito', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Campana', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Capira', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cermeño', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cirí de los Sotos', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cirí Grande', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Cacao', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Trinidad', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Ollas Arriba', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lídice', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Rosa', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Villa Carmen', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Villa Rosario', 'idDistrito' => 67, 'codigoUbicacion' => 'N/A'],
            //Chame
            ['name' => 'Bejuco', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Buenos Aires', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cabuya', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chame', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chicá', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Líbano', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Lajas', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nueva Gorgona', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Punta Chame', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sajalices', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sorá', 'idDistrito' => 68, 'codigoUbicacion' => 'N/A'],
            //Chorrera
            ['name' => 'Amador', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Arosemena', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barrio Balboa', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Barrio Colón', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Arado', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Coco', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Feuillet', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guadalupe', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Herrera', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hurtado', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Iturralde', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Chorrera', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Represa', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Díaz', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mendoza', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Obaldía', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Playa Leona', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Puerto Caimito', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Rita', 'idDistrito' => 69, 'codigoUbicacion' => 'N/A'],
            //San Carlos
            ['name' => 'El Espino', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Higo', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guayabito', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Ermita', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'La Laguna', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Las Uvas', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Los Llanitos', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Carlos', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San José', 'idDistrito' => 70, 'codigoUbicacion' => 'N/A'],

            //EMBERA WOUNAAN
            //Cemaco
            ['name' => 'Cirilo Guaynora', 'idDistrito' => 71, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lajas Blancas', 'idDistrito' => 71, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Manuel Ortega', 'idDistrito' => 71, 'codigoUbicacion' => 'N/A'],
            //Sambu
            ['name' => 'Río Sábalo', 'idDistrito' => 72, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Jingurudó', 'idDistrito' => 72, 'codigoUbicacion' => 'N/A'],

            //GUNA YALA
            //Guna Yala
            ['name' => 'Aligandí', 'idDistrito' => 73, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Narganá', 'idDistrito' => 73, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Puerto Obaldía', 'idDistrito' => 73, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tubualá', 'idDistrito' => 73, 'codigoUbicacion' => 'N/A'],

            //NGABE'BUGLE
            //Besiko
            ['name' => 'Boca de Balsa', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Camarón Arriba', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Banco', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro de Patena', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Emplanada de Chorcha', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nämnoni', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Niba', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Soloy', 'idDistrito' => 74, 'codigoUbicacion' => 'N/A'],
            //Jirondai
            ['name' => 'Bürí', 'idDistrito' => 75, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guariviara', 'idDistrito' => 75, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Man Creek', 'idDistrito' => 75, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Samboa', 'idDistrito' => 75, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tuwa', 'idDistrito' => 75, 'codigoUbicacion' => 'N/A'],
            //Kankintú
            ['name' => 'Bisira', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Calante', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guoroni', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Kankintú', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mününi', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Piedra Roja', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tolote', 'idDistrito' => 76, 'codigoUbicacion' => 'N/A'],
            //Kusapín
            ['name' => 'Bahía Azul', 'idDistrito' => 77, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cañavera', 'idDistrito' => 77, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Kusapín', 'idDistrito' => 77, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Río Chiriquí', 'idDistrito' => 77, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Tobobe', 'idDistrito' => 77, 'codigoUbicacion' => 'N/A'],
            //Mironó
            ['name' => 'Cascabel', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Corotú', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Culantro', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Jobo', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Julí', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Pilón', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Quebrada de Loro', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Salto Dupí', 'idDistrito' => 78, 'codigoUbicacion' => 'N/A'],
            //Müna
            ['name' => 'Alto Caballero', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Bakama', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Caña', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Puerco', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Chichica', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Dikeri', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Diko', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Kikari', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Krüa', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Maraca', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Mreeni', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Nibra', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Peña Blanca', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Roka', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Sitio Prado', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Ümani', 'idDistrito' => 79, 'codigoUbicacion' => 'N/A'],
            //Nole Duima
            ['name' => 'Cerro Iglesias', 'idDistrito' => 80, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Hato Chamí', 'idDistrito' => 80, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Jädaberi', 'idDistrito' => 80, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Lajero', 'idDistrito' => 80, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Susama', 'idDistrito' => 80, 'codigoUbicacion' => 'N/A'],
            //Ñürüm
            ['name' => 'Agua de Salud', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Alto de Jesús', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Buenos Aires', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Cerro Pelado', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Bale', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Paredón', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Piro', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Guayabito', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Güibale', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Peñon', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            ['name' => 'El Piro No.2 (Muakwata Kubu)', 'idDistrito' => 81, 'codigoUbicacion' => 'N/A'],
            //Santa Catalina
            ['name' => 'Alto Bilingüe', 'idDistrito' => 82, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Loma Yuca', 'idDistrito' => 82, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San Pedrito', 'idDistrito' => 82, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Santa Catalina', 'idDistrito' => 82, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Valle Bonito', 'idDistrito' => 82, 'codigoUbicacion' => 'N/A'],

            //NASO TJER DI
            //Naso Tjer Di
            ['name' => 'Bonyik', 'idDistrito' => 83, 'codigoUbicacion' => 'N/A'],
            ['name' => 'San San Drui', 'idDistrito' => 83, 'codigoUbicacion' => 'N/A'],
            ['name' => 'Teribe', 'idDistrito' => 83, 'codigoUbicacion' => 'N/A'],
        ]);
    }
}
